export const localization = {
    uk: {
        moreInfoBtn:         'Дізнатися більше',
        returnToMain:        'Перейти на головну',
        exchangeRate:        'Курси',
        currency:            'Валюта',
        cards:               'Картки',
        metals:              'Метали',
        ratesOn:             'Курси станом на',
        currencyConverter:   'Конвертер валют',
        give:                'Віддаємо',
        get:                 'Отримуємо',
        exchangeAmount:      'Сума обміну',
        whatWeGet:           'Що отримуємо',
        ratesArchive:        'Архів курса валют',
        buy:                 'Купівля',
        sale:                'Продаж',
        nbu:                 'НБУ',
        contributionName:    'Назва вкладу',
        ingotWeight:         'Маса зливка',
        salesRate:           'Курс продажу, грн/г',
        ingotCost:           'Вартiсть зливка, грн',
        Kyiv:                'Київ',
        forCalls:            'для дзвінків з інших областей України',
        IIB:                 'МІЖНАРОДНИЙ ІНВЕСТИЦІЙНИЙ БАНК Ліцензія НБУ № 242 від 15 листопада 2011 г.',
        development:         'Розробка',
        ratesInfo:           'Інформація про максимальні відсоткові ставки за вкладами фізичних осіб',
        codex:               'Кодекс корпоративновної поведінки',
        corporteCenter:      'Центр розкриття корпоративної інформації',
        followUs:            'Слідкуйте за нами в соц.мережах',
        searchResultsText:   'Знайдено результатів',
        searchResultsHeader: 'Результати пошуку',
        menu:                'Меню',
    },
    ru: {
        moreInfoBtn:         'Узнать больше',
        returnToMain:        'Перейти на головну',
        exchangeRate:        'Курсы',
        currency:            'Валюта',
        cards:               'Карточки',
        metals:              'Металлы',
        ratesOn:             'Курсы по состоянию на',
        currencyConverter:   'Конвертер валют',
        give:                'Отдаем',
        get:                 'Получаем',
        exchangeAmount:      'Сума обмена',
        whatWeGet:           'Что получаем',
        ratesArchive:        'Архив курсов валют',
        buy:                 'Покупка',
        sale:                'Продажа',
        nbu:                 'НБУ',
        contributionName:    'Название вклада',
        ingotWeight:         'Масса слитка',
        salesRate:           'Курс продажи грн/г',
        ingotCost:           'Стоимость слитка, грн',
        Kyiv:                'Киев',
        forCalls:            'для звонков из других областей Украины',
        IIB:                 'МЕЖДУНАРОДНЫЙ ИНВЕСТИЦИОННЫЙ БАНК Лицензия НБУ № 242 от 15 ноября 2011 г.',
        development:         'Разработка',
        ratesInfo:           'Информация о максимальных процентных ставок по вкладам физических лиц',
        codex:               'Кодекс корпоративновнои поведения',
        corporteCenter:      'Центр раскрытия корпоративной информации',
        followUs:            'Следите за нами в соц.сетях',
        searchResultsText:   'Найдено результатов',
        searchResultsHeader: 'Результаты поиска',
        menu:                'Меню',
    },
    en: {
        moreInfoBtn:         'More info',
        returnToMain:        'Go to home',
        exchangeRate:        'Rates',
        currency:            'Currency',
        cards:               'Cards',
        metals:              'Metals',
        ratesOn:             'The exchange rates as of',
        currencyConverter:   'Currency converter',
        give:                'Give',
        get:                 'Get',
        exchangeAmount:      'The amount of exchange',
        whatWeGet:           'What we get',
        ratesArchive:        'Exchange rates archive',
        buy:                 'Buy',
        sale:                'Sale',
        nbu:                 'NBU',
        contributionName:    'Name of contribution',
        ingotWeight:         'Ingot weight',
        salesRate:           'Sales rate, uah / g',
        ingotCost:           'Ingot cost, uah',
        Kyiv:                'Kyiv',
        forCalls:            'for calls from other regions of Ukraine',
        IIB:                 'INTERNATIONAL INVESTMENT BANK NBU License No. 242 of November 15, 2011',
        development:         'Development',
        ratesInfo:           'Information on maximum interest rates on deposits of individuals',
        codex:               'Code of Corporate Conduct',
        corporteCenter:      'Corporate Disclosure Center',
        followUs:            'Follow us on social networks',
        searchResultsText:   'Results found',
        searchResultsHeader: 'Search results',
        menu:                'Menu',
    },
}
;
